export const GET_ARTICLES = 'GET_ARTICLES';
export const CREATE_ARTICLE = 'CREATE_ARTICLE';
export const GET_ARTICLE = 'GET_ARTICLE';
export const GET_BOOKMARKS = 'GET_BOOKMARKS';
export const GET_BOOKMARKED_ERROR = 'GET_BOOKMARKED_ERROR';
