export const GET_CHAT_USERS = 'GET_CHAT_USERS';
export const GET_USERS_FAIL = 'GET_CHAT_USERS_FAIL';
export const GET_CURRENT_CHAT_USER = 'GET_CURRENT_CHAT_USER';
export const GET_CHAT_MESSAGES = 'GET_CHAT_MESSAGES';
export const CHAT_USERS_PENDING = 'CHAT_USERS_PENDING';
export const CHAT_MESSAGES_PENDING = 'CHAT_MESSAGES_PENDING';
export const CURRENT_CHAT_USER_FAIL = 'CHAT_USER_FAIL';
