export const LIKE_ARTICLE_SUCCESS = 'LIKE_ARTICLE_START';
export const LIKE_ARTICLE_FAILURE = 'LIKE_ARTICLE_FAILURE';

export const DISLIKE_ARTICLE_SUCCESS = 'DISLIKE_ARTICLE_START';
export const DISLIKE_ARTICLE_FAILURE = 'DISLIKE_ARTICLE_FAILURE';

export const GET_ARTICLE_LIKES_SUCCESS = 'GET_ARTICLE_LIKES_SUCCESS';
export const GET_ARTICLE_LIKES_FAILURE = 'GET_ARTICLE_LIKES_FAILURE';

export const GET_ARTICLE_DISLIKES_SUCCESS = 'GET_ARTICLE_DISLIKES_SUCCESS';
export const GET_ARTICLE_DISLIKES_FAILURE = 'GET_ARTICLE_DISLIKES_FAILURE';
