export const GET_UNREAD_NOTIFICATIONS = 'GET_UNREAD_NOTIFICATIONS';
export const GET_UNREAD_NOTIFICATIONS_COUNT = 'GET_UNREAD_NOTIFICATIONS_COUNT';
export const READ_NOTIFICATION = 'READ_NOTIFICATION';
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
