export const OPTED_IN_EMAIL = 'OPTED_IN_EMAIL';
export const OPTED_OUT_EMAIL = 'OPTED_OUT_EMAIL';
export const OPTED_IN_APP = 'OPTED_IN_APP';
export const OPTED_OUT_APP = 'OPTED_OUT_APP';
export const ALREADY_OPTED_IN_APP = 'ALREADY_OPTED_IN_APP';
export const ALREADY_OPTED_IN_EMAIL = 'ALREADY_OPTED_IN_EMAIL';
